version: "3.8"

services:
  devcontainer:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/workspace:rw
      - ~/.ssh:/home/vscode/.ssh:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 4000:4000
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
